# Generated by Django 6.0.3 on 2026-05-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='donors/docs/'),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='donors/'),
        ),
    ]
