# Generated by Django 6.0.3 on 2026-05-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donor_document_donor_email_donor_phone_and_more'),
        ('projects', '0003_alter_donation_donor_delete_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
