# Generated by Django 6.0.3 on 2026-03-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beneficiary',
        ),
    ]
