# Generated by Django 6.0.3 on 2026-05-12 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donor_document_donor_email_donor_phone_and_more'),
        ('projects', '0002_delete_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor'),
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
