# Generated by Django 6.0.3 on 2026-05-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donor_donation_amount_alter_donor_project'),
        ('projects', '0003_alter_donation_donor_delete_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donor'),
        ),
    ]
