# Generated by Django 6.0.3 on 2026-05-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='courses_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='literacy_level',
            field=models.CharField(choices=[('None', 'None'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher', 'Higher')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='training_history',
            field=models.TextField(blank=True),
        ),
    ]
